# Site settings
title: jsless pattern library
email: mail@harrypujols.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of UI patterns done entirelly in css
baseurl: "/jsless" # the subpath of your site, e.g. /blog
url: "http://harrypujols.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: harrypujols
github_username:  harrypujols

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    style: expanded
    sass_dir: _sass

livereload: true
